// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fpazipkhxsxcghwdnvqq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZwYXppcGtoeHN4Y2dod2RudnFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NTQ5MDcsImV4cCI6MjA2NTEzMDkwN30.7aORFpQa_r3h8gezJeGmYpCr9pRixX6t73oEBNqCfHo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);